name: swapi_client
description: A library that makes it easy to fetch data from SWAPI - The Star Wars API.
version: 0.1.0
homepage: https://github.com/brianegan/swapi_client
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.0.0